$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "############################################" -ForegroundColor Cyan
Write-Host "   Hawk.ai  -  LAN + Cloudflare Tunnel" -ForegroundColor Cyan
Write-Host "############################################" -ForegroundColor Cyan
Write-Host ""

# --- Prerequisites -------------------------------------------------------
foreach ($cmd in @("python", "node", "cloudflared")) {
    try {
        $ver = & $cmd --version 2>&1
        Write-Host "  OK  $cmd : $ver" -ForegroundColor Green
    }
    catch {
        Write-Host "  ERROR  '$cmd' not found in PATH." -ForegroundColor Red
        if ($cmd -eq "cloudflared") {
            Write-Host "  Download: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/" -ForegroundColor Yellow
        }
        Read-Host "Press Enter to exit"
        exit 1
    }
}

Write-Host ""

# --- Get LAN IP (fast method using ipconfig instead of Get-NetIPAddress) --
try {
    $lanIP = (ipconfig | Select-String "IPv4" | Where-Object { $_ -notmatch "127\.0\.0\.1" } | Select-Object -First 1) -replace ".*:\s*", "" -replace "\s+", ""
    if (-not $lanIP) { $lanIP = "YOUR-PC-IP" }
}
catch {
    $lanIP = "YOUR-PC-IP"
}
Write-Host "  LAN IP: $lanIP" -ForegroundColor DarkCyan

# --- venv check ----------------------------------------------------------
$backendDir = ".\backend"
if (-not (Test-Path "$backendDir\venv\Scripts\python.exe")) {
    Write-Host ""
    Write-Host "  ERROR  venv not found at $backendDir\venv" -ForegroundColor Red
    Write-Host "  Run these commands first:" -ForegroundColor Yellow
    Write-Host "    cd backend" -ForegroundColor White
    Write-Host "    python -m venv venv" -ForegroundColor White
    Write-Host "    venv\Scripts\activate" -ForegroundColor White
    Write-Host "    pip install -r requirements.txt" -ForegroundColor White
    Read-Host "Press Enter to exit"
    exit 1
}

# --- 1/3  Start FastAPI Backend (in its own window) ----------------------
Write-Host ""
Write-Host "[1/3] Launching FastAPI backend in new window ..." -ForegroundColor Yellow

$backendAbsDir = (Resolve-Path $backendDir).Path
Start-Process "cmd.exe" -ArgumentList "/k cd /d `"$backendAbsDir`" && .\\venv\\Scripts\\activate && set RTSP_URL= && python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload" -WindowStyle Normal

Write-Host "  OK  Backend window opened. Waiting 6s for it to boot..." -ForegroundColor Green
Start-Sleep -Seconds 6

# --- 2/3  Start Cloudflared Tunnel (capture URL from log file) -----------
Write-Host ""
Write-Host "[2/3] Starting Cloudflare tunnel -> http://localhost:8000 ..." -ForegroundColor Yellow

$cfLog = "$env:TEMP\hawk_cloudflared.log"
if (Test-Path $cfLog) { Remove-Item $cfLog -Force }

# Launch cloudflared in its own window (stderr is where the URL appears)
# We also redirect stderr to file to capture the URL
Start-Process "cmd.exe" `
    -ArgumentList "/c cloudflared tunnel --url http://localhost:8000 --no-autoupdate 2>`"$cfLog`"" `
    -WindowStyle Minimized

Write-Host "  Waiting for tunnel URL (up to 30s)..." -ForegroundColor DarkGray

$tunnelUrl = $null
$deadline = (Get-Date).AddSeconds(30)
while (((Get-Date) -lt $deadline) -and (-not $tunnelUrl)) {
    Start-Sleep -Milliseconds 600
    if (Test-Path $cfLog) {
        try {
            $content = [System.IO.File]::ReadAllText($cfLog)
            if ($content -match "https://[a-z0-9\-]+\.trycloudflare\.com") {
                $tunnelUrl = $Matches[0]
            }
        }
        catch { }
    }
}

if (-not $tunnelUrl) {
    Write-Host ""
    Write-Host "  Could not auto-detect tunnel URL." -ForegroundColor Yellow
    Write-Host "  Check the cloudflared window or log: $cfLog" -ForegroundColor DarkGray
    $tunnelUrl = Read-Host "  Paste the tunnel URL (e.g. https://xxxx.trycloudflare.com) or press Enter to use localhost"
    if (-not $tunnelUrl) { $tunnelUrl = "http://localhost:8000" }
}

Write-Host ""
Write-Host "  >> Tunnel URL: $tunnelUrl" -ForegroundColor Cyan

# --- Write .env.local ----------------------------------------------------
$date = Get-Date -Format "yyyy-MM-dd HH:mm"
$envLines = @(
    "# Auto-generated by start-hawk-lan.ps1 on $date",
    "BACKEND_URL=$tunnelUrl",
    "NEXT_PUBLIC_API_URL=$tunnelUrl",
    "RTSP_URL="
)
$envLines | Set-Content -Path ".\.env.local" -Encoding UTF8
Write-Host "  .env.local updated." -ForegroundColor Green

# --- 3/3  Start Next.js Frontend (in its own window) ---------------------
Write-Host ""
Write-Host "[3/3] Launching Next.js frontend in new window ..." -ForegroundColor Yellow

$npmCmd = if (Get-Command "pnpm" -ErrorAction SilentlyContinue) { "pnpm" } else { "npm" }
$rootDir = (Get-Location).Path
Start-Process "cmd.exe" -ArgumentList "/k cd /d `"$rootDir`" && $npmCmd run dev" -WindowStyle Normal

Write-Host "  OK  Frontend window opened." -ForegroundColor Green

# --- Summary -------------------------------------------------------------
Write-Host ""
Write-Host "############################################" -ForegroundColor Cyan
Write-Host "   Hawk.ai is running!" -ForegroundColor Cyan
Write-Host "############################################" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Teacher Dashboard (this PC):" -ForegroundColor White
Write-Host "    http://localhost:3000" -ForegroundColor Green
Write-Host ""
Write-Host "  Backend API (tunnel):" -ForegroundColor White
Write-Host "    $tunnelUrl" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Smart Board Page (open on Smart Board browser):" -ForegroundColor White
Write-Host "    http://${lanIP}:3000/smartboard" -ForegroundColor Cyan
Write-Host ""
Write-Host "============================================" -ForegroundColor Yellow
Write-Host "  Share backend tunnel with Smart Boards:" -ForegroundColor Yellow
Write-Host "  $tunnelUrl" -ForegroundColor Yellow
Write-Host "============================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Each service is running in its own CMD window." -ForegroundColor DarkGray
Write-Host "  Close those windows to stop the services." -ForegroundColor DarkGray
Write-Host ""

Read-Host "Press Enter to exit this launcher"
